language: go

go:
  - 1.x

cache:
  directories:
    - $GOPATH/src
    - $GOPATH/pkg

notifications:
  email: false

before_install:
  - echo "Do nothing"

before_script:
  - go get -u -v github.com/spf13/hugo

script:
  - bash ./deploy.sh

env:
  global:
  - ENCRYPTION_LABEL: "71485ef889a6"
  - COMMIT_AUTHOR_EMAIL: "admin@eestec.be"
