baseurl = "http://www.eestec.be"
languageCode = "be-nl"
title = "EESTEC Antwerpen"
theme = "herring-cove"
copyright = "<a rel=\"license\" href=\"http://creativecommons.org/licenses/by-sa/4.0/\"><img alt=\"Creative Commons License\" style=\"border-width:0\" src=\"/img/cc.png\" /></a> This work by <a xmlns:cc=\"http://creativecommons.org/ns#\" href=\"www.eestec.be\" property=\"cc:attributionName\" rel=\"cc:attributionURL\">EESTEC Antwerp</a> is licensed under a <a rel=\"license\" href=\"http://creativecommons.org/licenses/by-sa/4.0/\">Creative Commons Attribution-ShareAlike 4.0 International License</a>."

[[menu.main]]
    name        = "Home"
    url         = "/"
    weight      = -1

[params]
    description = ""
    logo        = "/img/logo.svg"
    twitter     = "eestecantwerp"
    facebook    = "https://www.facebook.com/eestecantwerp"
    showcase    = "Welcome to EESTEC Antwerpen!"
    rss         = "/index.xml"
    contact     = "mailto:board@eestec.be"
